//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_UserProjectMapping :IEntity
    {
        public int UserProjectMapID { get; set; }
        public int ProjectID { get; set; }
        public int ClientID { get; set; }
        public EntityState EntityState { get; set; }
    }
}
